### ISSUE TITLE
simple doorways instead of interiors/exteriors

### ISSUE THREAD

**Issue by Shares5** [MattJeanes/Doors#1]
Firstly I apologise if this isn't the correct place for a feature request.

I've figured out how to modify the interior/exterior models of the tardis so that I can create my own world portals although I was hoping there would be a method that would allow 2 movable doorways to travel between rather than an external doorway model and an internal room model.

I feel like it should be possible although i'm not sure if its simply me not knowing how or if its hard coded to be this way, any input on the matter would be greatly appreciated

**Comment by MattJeanes** [comment]
This would be a different addon that used world-portals, which I have thought about making if you want to give it a go, below is the world-portals addon used for the portals in the doors and tardis addons:

https://github.com/MattJeanes/world-portals/tree/teleport-beta

**Comment by Shares5** [comment]
ahh, fair enough. after staring through the tardis code for hours I figure I wouldn't know where to start though. Thanks for the prompt response

**Comment by MattJeanes** [comment]
No problem. Below is the section of Doors which spawns the portals, and links them together - you may find it useful:

https://github.com/MattJeanes/Doors/blob/master/lua/entities/gmod_door_interior/modules/sh_portals.lua#L24-L69

If you decide to make anything then good luck, I'll probably get round to it at some point anyway though.

**Comment by Shares5** [comment]
thank you! that should help a lot

**Comment by Shares5** [comment]
http://i.imgur.com/stofTMX.jpg woo! lol, i used lines 24 - 36 of the code you linked, are you happy for me to put it on the workshop and stuff?

**Comment by MattJeanes** [comment]
Sure, credit bliptec mainly as he's the one who did the majority of work on the portals. You might have to make 'Doors' a required addon so people get the world-portals addon installed. Currently world-portals is bundled in Doors but in future it may be uploaded separately.

**Comment by MattJeanes** [comment]
Looks good by the way!
